### ISSUE TITLE
groupby on sorted data

### ISSUE THREAD

**Issue by brentp** [narimiran/itertools#8]
a key feature of python's itertools.groupby is that it operates on and returns iterators, lazily consuming the input. would you consider supporting that? where the input is assumed to be sorted by the same key/fn as the grouping?

**Comment by narimiran** [comment]
If I understand it correctly, this is now implemented via `groupConsecutive` (because I didn't want to break the behaviour of the existing `groupBy`).

Please see [the documentation](https://narimiran.github.io/itertools/#groupConsecutive.i%2CopenArray%5BT%5D) (there are two iterators by the same name), and tell me if this is what you wanted.
If the same keys are not grouped/sorted beforehand, they will be treated as a separate group, e.g.:

```nim
for key, group in groupConsecutive("aaabaabb"):
  echo group
# @['a', 'a', 'a']; @['b']; @['a', 'a']; @['b', 'b']
```


Sorry it took this long.

**Comment by brentp** [comment]
yes! thank you!
